apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm2.fullname" . }}-apiserver
  labels:
    app: apiserver
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include ".helm2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: apiserver
        {{- include ".helm2.selectorLabels" . | nindent 8 }}
    spec:         
      containers:       
      - name: fonos
        image: fonoster/apiserver:latest
        imagePullPolicy: Always
        env:
        - name: SIPPROXY_HOST
          value: {{ include ".helm2.fullname" . }}-sipproxy.{{ .Release.Namespace }}.svc.cluster.local
        - name: MS_ENDPOINT  # Fixme
          value: sip:ast@sip.local 
        - name: DS_HOST
          value: {{ printf "%s-%s" .Release.Name .Values.redis.nameOverride }}-master
        - name: DS_PORT
          value: "6379"
        - name: SIPPROXY_API_PORT
          value: "4567"
        - name: SIPPROXY_API_USERNAME
          value: admin
        - name: SIPPROXY_API_SECRET
          value: changeit
        - name: FS_HOST
          value: {{ printf "%s-%s" .Release.Name .Values.minio.nameOverride }}
        - name: FS_PORT
          value: "9000"
        - name: FS_USERNAME
          value: minio
        - name: FS_SECRET
          value: minio123
        - name: FS_DEFAULT_STORAGE_BUCKET
          value: default
        - name: EVENTS_BROKERS
          value: amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ printf "%s-%s" .Release.Name .Values.rabbitmq.nameOverride }}:5672  
        volumeMounts:
        - mountPath: /root/.fonoster
          name: fonoster-config
          readOnly: true
        ports:
        - name: grpc
          containerPort: 50052
      volumes:
      - name: fonoster-config
        secret:
          secretName: fonoster-config
