apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm2.fullname" . }}-mediacontroller
  labels:
    app: mediacontroller
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include ".helm2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: mediacontroller
        {{- include ".helm2.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: mediacontroller
        image: fonoster/nodejsmc:latest
        imagePullPolicy: Always
        env:
        - name: APISERVER_ENDPOINT
          value: "{{ include ".helm2.fullname" . }}-apiserver:50052"
        - name: TTS_ENGINE_HOST
          value: {{ include ".helm2.fullname" . }}-ttsengine
        - name: TTS_ENGINE_PORT
          value: "59125"
        - name: EVENTS_BROKERS
          value: amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ printf "%s-%s" .Release.Name .Values.rabbitmq.nameOverride }}:5672
        - name: EVENTS_QUEUE
          value: apiserver
        volumeMounts:
          - mountPath: /root/.fonoster
            name: fonoster-config
            readOnly: true
          - mountPath: /fonoster
            name: shared-files
            readOnly: false
        ports:
        - name: agi
          containerPort: 4573
      - name: chmodhelper
        image: fonoster/chmodhelper:latest
        imagePullPolicy: Always
        env:
          - name: EVENTS_BROKERS
            value: amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ printf "%s-%s" .Release.Name .Values.rabbitmq.nameOverride }}:5672    
        volumeMounts:
          - mountPath: /data
            name: shared-files
            readOnly: false
      volumes:
        - name: fonoster-config
          secret:
            secretName: fonoster-config
        - name: shared-files
          persistentVolumeClaim:
            claimName: {{ printf "%s-%s" .Release.Name .Values.minio.nameOverride }}