# Required dependencies

version: '3.7'

networks:
  fonoster:

volumes:
  datasource:
    external: true

services:

  datasource:
    image: fonoster/redis:${COMPOSE_PROJECT_VERSION}
    restart: ${RESTART_POLICY}
    command: ['redis-server', '/etc/redis/redis.conf' ]
    healthcheck:
      test: ['CMD', 'redis-cli','ping']
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.datasource
    networks:
      fonoster:
        aliases: 
          - ${DS_HOST}
    volumes: 
      - ${CONFIG}/redis.conf:/etc/redis/redis.conf:ro
      - datasource:/data