# Vault Initialization script

version: '3.7'

networks:
  fonoster:

services:

  secrets_init:
    image: fonoster/secrets:${COMPOSE_PROJECT_VERSION}
    entrypoint: /bin/sh -c "init"
    networks:
      fonoster:
