# Optional TTS Engine (MaryTTS)

version: '3.7'

networks:
  fonoster:

services:

  tts:
    image: fonoster/marytts:${COMPOSE_PROJECT_VERSION}
    restart: ${RESTART_POLICY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tts.entrypoints=internal,websecure"
      - "traefik.http.routers.tts.rule=PathPrefix(`/process`)"
      - "traefik.http.services.tts.loadbalancer.server.port=59125"
      - "traefik.http.routers.tts.middlewares=session-auth@docker"
      - "traefik.http.middlewares.session-auth.forwardauth.address=http://auth:3000/session_auth"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${TTS_ENGINE_PORT}"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      fonoster:
        aliases: 
          - ${TTS_ENGINE_HOST}
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.tts
